.TH dualcoax 1 "atlc-4.6.0 28th Oct 2003" "Dr. David Kirkby"
.ds n 5
.SH NAME
\fBdualcoax\fR - determine impedance of a coaxial structure with two concentric dielectrics.
.SH SYNOPSIS
\fBdualcoax D1 D2 D3 Er1 Er2\fR
.br
.SH DESCRIPTION
dualcoax computes the impedaance of a dualcoaxial cable, with two 
concentric dielectrics, given the outside diameter of the inner conductor D1, 
the outside diameter of the inner dielectric D2, the  
outside diameter of the outer dielectric (which is also the inside diameter of the 
outer conductor) D3, as well as the relative permttivity of the inner 
dielectric Er1 and the outer dielectric Er2.
.br
.br
.SH FILES 
dualcoax does not read/write any files. 
.SH SEE ALSO
atlc(1)
.br
coax(1)
.br
create_bmp_for_circ_in_circ(1)
.br
create_bmp_for_circ_in_rect(1)
.br
create_bmp_for_microstrip_coupler(1)
.br
create_bmp_for_rect_cen_in_rect(1)
.br
create_bmp_for_rect_cen_in_rect_coupler(1)
.br
create_bmp_for_rect_in_circ(1)
.br
create_bmp_for_rect_in_rect(1)
.br
create_bmp_for_stripline_coupler(1)
.br
create_bmp_for_symmetrical_stripline(1)
.br
design_coupler(1)
.br
find_optimal_dimensions_for_microstrip_coupler(1)
.br
readbin(1)
.P 
.br
http://atlc.sourceforge.net      - Home page 
.br
http://sourceforge.net/projects/atlc   - Download area
.br
/usr/local/share/atlc/docs/html-docs/index.html  - HTML docs
.br
/usr/local/share/atlc/docs/qex-december-1996/atlc.pdf - theory paper
.br
/usr/local/share/atlc/examples    - examples
.br
